### PR TITLE
possible broken rss feed fix

### PR DESCRIPTION
**Pull request by vladserkoff**
Hi! I'm subscribed to your blog via rss feed but the links in it are broken and look like this one
http://koaning.io/feeds/koaning.io/koaning.io/blender-trees.html

I'm not able to test it on my machine, but it looks like that the issue is as described in this link
http://docs.getpelican.com/en/3.6.3/faq.html#i-m-getting-a-warning-about-feeds-generated-without-siteurl-being-set-properly

### CODE REVIEW

**Comment by koaning** [comment]
worth a try. thanks!

**Comment by koaning** [comment]
just uploaded. is the RSS feed fixed?

**Comment by vladserkoff** [comment]
it's not, unfortunately. but i can't really pin the problem, as i've never used pelican or whatever. this was just a guess. well, i'll continue to manually change the urls :smile:

**Comment by koaning** [comment]
yeah. i've tried a bunch of that pelican stuff and it never really worked. i'll have another look at it sometime later. glad to hear you like the blog tho.

**Pull request merged**
